@extends('layouts.app')

@section('content')
<div class="page-header">
    <div>
        <div class="pill">DSWD Assistance View</div>
        <h1>Resource Recommendations</h1>
        <p class="muted">Validated disaster recommendations for food packs, medicine kits, and cash assistance coordination.</p>
    </div>
</div>

<div class="stats-grid">
    <div class="stat-card">
        <span>Recommendations</span>
        <strong>{{ $stats['recommendations'] }}</strong>
    </div>
    <div class="stat-card">
        <span>Covered Barangays</span>
        <strong>{{ $stats['covered_barangays'] }}</strong>
    </div>
    <div class="stat-card">
        <span>Affected Families</span>
        <strong>{{ $stats['families'] }}</strong>
    </div>
    <div class="stat-card">
        <span>Cash Assistance</span>
        <strong>Php {{ number_format($stats['cash_assistance'], 2) }}</strong>
    </div>
</div>

<section class="card">
    <div class="section-heading">
        <div>
            <h2>Recommendation Records</h2>
            <p class="muted">Use this validated-only list for relief planning, release coordination, and case review.</p>
        </div>
    </div>

    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>Recommendation</th>
                    <th>Report</th>
                    <th>Barangay</th>
                    <th>Disaster Type</th>
                    <th>Priority</th>
                    <th>Families</th>
                    <th>Members</th>
                    <th>Food Packs</th>
                    <th>Medicine Kits</th>
                    <th>Cash Assistance</th>
                    <th>Basis</th>
                    <th>Validated By</th>
                    <th>Generated By</th>
                </tr>
            </thead>
            <tbody>
                @forelse($recommendations as $row)
                    <tr>
                        <td>{{ $row['id'] }}</td>
                        <td>{{ $row['report'] }}</td>
                        <td>{{ $row['barangay'] }}</td>
                        <td>{{ $row['disaster_type'] }}</td>
                        <td>{{ $row['severity'] }}</td>
                        <td>{{ $row['families'] }}</td>
                        <td>{{ $row['members'] }}</td>
                        <td>{{ $row['food_packs'] }}</td>
                        <td>{{ $row['medicine_kits'] }}</td>
                        <td>Php {{ number_format($row['cash_assistance'], 2) }}</td>
                        <td>{{ $row['basis'] }}</td>
                        <td>
                            {{ $row['validated_by'] }}
                            <br><small>{{ $row['validated_at_label'] }}</small>
                        </td>
                        <td>{{ $row['generated_by'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="13">No validated recommendations found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</section>
@endsection
