@extends('layouts.app')

@section('content')
<div class="page-header">
    <div>
        <div class="pill">DSWD Assistance View</div>
        <h1>Resource Recommendations</h1>
        <p class="muted">Recommended food packs, medicine kits, and cash assistance for affected families.</p>
    </div>
</div>

<section class="card">
    <div class="section-heading">
        <div>
            <h2>Recommendation Records</h2>
            <p class="muted">Use this list for relief planning and release coordination.</p>
        </div>
    </div>

    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>Recommendation</th>
                    <th>Report</th>
                    <th>Barangay</th>
                    <th>Families</th>
                    <th>Members</th>
                    <th>Food Packs</th>
                    <th>Medicine Kits</th>
                    <th>Cash Assistance</th>
                    <th>Generated By</th>
                </tr>
            </thead>
            <tbody>
                @forelse($recommendations as $row)
                    <tr>
                        <td>{{ $row['id'] }}</td>
                        <td>{{ $row['report'] }}</td>
                        <td>{{ $row['barangay'] }}</td>
                        <td>{{ $row['families'] }}</td>
                        <td>{{ $row['members'] }}</td>
                        <td>{{ $row['food_packs'] }}</td>
                        <td>{{ $row['medicine_kits'] }}</td>
                        <td>Php {{ number_format($row['cash_assistance'], 2) }}</td>
                        <td>{{ $row['generated_by'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9">No recommendations found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</section>
@endsection
