@extends('layouts.app')

@section('content')
<div class="page-header">
    <div>
        <div class="pill">Admin Oversight</div>
        <h1>Recommendation History</h1>
        <p class="muted">View all generated recommendations, track triggered rules, and review past decision-support outputs.</p>
    </div>
</div>

<div class="stats-grid">
    <div class="stat-card">
        <span>Total Recommendations</span>
        <strong>{{ $stats['total'] }}</strong>
    </div>
    <div class="stat-card">
        <span>High Priority Outputs</span>
        <strong>{{ $stats['high_priority'] }}</strong>
    </div>
    <div class="stat-card">
        <span>Total Food Packs</span>
        <strong>{{ $stats['food_packs'] }}</strong>
    </div>
    <div class="stat-card">
        <span>Total Cash Assistance</span>
        <strong>Php {{ number_format($stats['cash_assistance'], 2) }}</strong>
    </div>
</div>

<div class="content-grid two-columns">
    <section class="card">
        <div class="section-heading">
            <div>
                <h2>Generated Recommendation Outputs</h2>
                <p class="muted">Audit view of all decision-support outputs generated for disaster reports.</p>
            </div>
        </div>

        <div class="table-wrap">
            <table>
                <thead>
                    <tr>
                        <th>Recommendation ID</th>
                        <th>Report</th>
                        <th>Barangay</th>
                        <th>Type</th>
                        <th>Priority</th>
                        <th>Food Packs</th>
                        <th>Medicine Kits</th>
                        <th>Cash Assistance</th>
                        <th>Generated By</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($recommendations as $item)
                        <tr>
                            <td>{{ $item['id'] }}</td>
                            <td>{{ $item['report'] }}</td>
                            <td>{{ $item['barangay'] }}</td>
                            <td>{{ $item['disaster_type'] }}</td>
                            <td>{{ $item['severity'] }}</td>
                            <td>{{ $item['food_packs'] }}</td>
                            <td>{{ $item['medicine_kits'] }}</td>
                            <td>Php {{ number_format($item['cash_assistance'], 2) }}</td>
                            <td>{{ $item['generated_by'] }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="9">No recommendation history found.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </section>

    <section class="card">
        <div class="section-heading">
            <div>
                <h2>Triggered Rule Reference</h2>
                <p class="muted">Decision Tree rules used as the basis for recommendation generation.</p>
            </div>
        </div>

        <div class="stack-list">
            @foreach($rules as $rule)
                <div class="stack-item">
                    <div class="stack-head">
                        <strong>Rule {{ $rule['id'] }}</strong>
                        <span class="badge badge-blue">Decision Tree</span>
                    </div>
                    <p><strong>Condition:</strong> {{ $rule['condition'] }}</p>
                    <p class="item-note"><strong>Logic:</strong> {{ $rule['logic'] }}</p>
                    <p class="item-note"><strong>Output:</strong> {{ $rule['output'] }}</p>
                </div>
            @endforeach
        </div>
    </section>
</div>

<section class="card top-gap">
    <div class="section-heading">
        <div>
            <h2>Decision-Support History Review</h2>
            <p class="muted">Past outputs with report context, triggered rule summary, and generation details.</p>
        </div>
    </div>

    <div class="stack-list">
        @forelse($recommendations as $item)
            <div class="stack-item">
                <div class="stack-head">
                    <div>
                        <strong>{{ $item['id'] }} | {{ $item['report'] }} | {{ $item['barangay'] }}</strong>
                        <p class="muted">{{ $item['disaster_type'] }} | {{ $item['status'] }} | {{ $item['generated_at'] }}</p>
                    </div>
                    <span class="badge badge-{{ strtolower($item['severity']) === 'high' ? 'red' : (strtolower($item['severity']) === 'medium' ? 'amber' : 'green') }}">{{ $item['severity'] }}</span>
                </div>

                <div class="mini-grid">
                    <div><span>Affected Families</span><strong>{{ $item['families'] }}</strong></div>
                    <div><span>Household Members</span><strong>{{ $item['members'] }}</strong></div>
                    <div><span>Affected Structures</span><strong>{{ $item['structures'] }}</strong></div>
                </div>

                <p class="item-note"><strong>Triggered Rule:</strong> {{ $item['rule_trigger'] }}</p>
                <p class="item-note"><strong>Output Summary:</strong> {{ $item['output_summary'] }}</p>
                <p class="item-note"><strong>Basis:</strong> {{ $item['basis'] }}</p>
            </div>
        @empty
            <div class="stack-item">
                <strong>No decision-support outputs yet.</strong>
                <p class="muted">Generated recommendations will appear here for admin review.</p>
            </div>
        @endforelse
    </div>
</section>
@endsection
